services:
    tienvx_mbt.expression_language:
        class: Symfony\Component\ExpressionLanguage\ExpressionLanguage
    tienvx_mbt.audit_trail_listener:
        class: Tienvx\Bundle\MbtBundle\EventListener\WorkflowListener
        tags:
            - { name: kernel.event_subscriber }
