language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  - composer install

script: phpunit --coverage-clover ./tests/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
