language: php

php:
  - 7.1
  - 7.2
  #- 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly
  include:
    - php: 7.3
      env: dependencies="--ignore-platform-reqs"

install:
  - composer install $dependencies

script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then composer run-script cs-fix; fi
  - composer run-script coverage --timeout=0

after_success:
  - travis_retry composer run-script coverall
