language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  - composer install

script:
  - composer run-script cs-fix
  - composer run-script coverage --timeout=0

after_success:
  - travis_retry composer run-script coverall
