services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Tienvx\Bundle\MbtBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Resources}'
    Symfony\Component\ExpressionLanguage\ExpressionLanguage:
        class: Symfony\Component\ExpressionLanguage\ExpressionLanguage
