services:
    tienvx_mbt.expression_language:
        class: Symfony\Component\ExpressionLanguage\ExpressionLanguage
    tienvx_mbt.workflow_listener:
        class: Tienvx\Bundle\MbtBundle\EventListener\WorkflowListener
        tags:
            - { name: kernel.event_subscriber }
    tienvx_mbt.data_provider:
        class: Tienvx\Bundle\MbtBundle\Service\DataProvider
    tienvx_mbt.graph_builder:
        class: Tienvx\Bundle\MbtBundle\Service\GraphBuilder
    tienvx_mbt.traversal_factory:
        class: Tienvx\Bundle\MbtBundle\Service\TraversalFactory
        arguments:
            - '@tienvx_mbt.data_provider'
            - '@tienvx_mbt.graph_builder'
    tienvx_mbt.path_runner:
        class: Tienvx\Bundle\MbtBundle\Service\PathRunner
        arguments:
            - '@tienvx_mbt.data_provider'
    tienvx_mbt.path_reducer:
        class: Tienvx\Bundle\MbtBundle\Service\PathReducer
        arguments:
            - '@tienvx_mbt.path_runner'
