resources:
    Tienvx\Bundle\MbtBundle\Entity\Task:
        shortName: 'Task'
        description: 'A task tell use which model to test and how to test that model'
        iri: 'http://schema.org/Task'
        attributes:
            pagination_items_per_page: 10
    Tienvx\Bundle\MbtBundle\Entity\Bug:
        shortName: 'Bug'
        description: 'A bug discovered from running a task'
        iri: 'http://schema.org/Bug'
        attributes:
            pagination_items_per_page: 10
