name: main

on: [push, pull_request]

jobs:
  php-cs-fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: PHP CS Fixer
      uses: docker://oskarstark/php-cs-fixer-ga
      with:
        args: --diff --dry-run

  phpinsights:
    name: PHP Insights
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: PHP Insights
      uses: docker://tienvx/phpinsights-action
      with:
        args: "-v --min-quality=70 --min-complexity=70 --min-architecture=50 --min-style=80"

  test:
    name: Test PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4.0RC6']
    container:
      image: php:${{ matrix.php }}-cli-alpine
    steps:
    - name: Set Up Container
      run: |
        apk add -q --no-cache $PHPIZE_DEPS git bash
        pecl install pcov > /dev/null
        docker-php-ext-enable pcov
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
        composer global require hirak/prestissimo > /dev/null

    - name: Checkout
      uses: actions/checkout@master

    - name: Install Dependencies
      run: composer install

    - name: Test & Generate Code Coverage
      run: |
        wget -q -O phpunit https://phar.phpunit.de/phpunit-8.phar
        chmod +x phpunit
        ./phpunit -d memory_limit=256M --coverage-clover tests/logs/clover.xml

    - name: Submit Code Coverage
      run: |
        wget -q -O codecov.sh https://codecov.io/bash
        chmod +x codecov.sh
        ./codecov.sh -f tests/logs/clover.xml -t $CODECOV_TOKEN
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      if: matrix.php == '7.3' && github.event_name == 'push'
